### PR TITLE
Added SystemD fix

### PR DESCRIPTION
**Pull request by jman6495**
SystemD fix ! Hope this will be of use.
At the moment the systemd package is on my dropbox, request a merge some time this week with the package in it so that we don't have to rely on dropbox.

### CODE REVIEW

**Comment by omgmog** [comment]
We could use a version of the package hosted on a rollback mirror, such as http://rollback.adminempire.com/2014/06/03/armv7h/core/systemd-212-3-armv7h.pkg.tar.xz, or alternatively upload the package to the repo and link straight from Github

**Comment by jman6495** [comment]
Ohh I figured that the rollback mirror packages were erased over time ? If not then I suppose that's the best way forward. Sadly  I don't have git availible right now (at university) so All my edits have to be done via the webUI. The Issue is uploading files via the webUI isn't possible.

**Comment by omgmog** [comment]
Okay well I've uploaded the package to the repository in c79f3e66d97c67119471b8fe52d4d3c71399e982, so we should be in a working `systemd` state with your change. I'll need to give it a run on my Chromebook when I have a moment though.

**Comment by omgmog** [comment]
Maybe it would be better to create `chrootscript.sh` as a file in the repo, rather than creating it using echo, then simply `wget` it as we need it. Would make it clearer as to what is going on, and easier to maintain.

**Comment by jman6495** [comment]
This Pull request is outdated.

**Pull request closed without merging**
