### PR TITLE
Seperate partition script, fixed systemd, added prompt to choose a root password

### PR DESCRIPTION
**Pull request by jman6495**
I made quite a few changes.
I've been experimenting with partx, but have found it about as useful as a legless man at an ass kicking competition. It failed to partition 2 of my 4 USB sticks, and even failed to recognise several of them. (when parted worked fine)

In order to at least (temporarily) fix the problem described in #14 , i've commented out all the partitioning commands in install.sh and created a script that should be run from a normal linux install outside of the chromebook, that prepares the USB sticks partitions. 
i'm proposing this but *with caution*. I don't know if this is the best solution to the problem and I'm scared it'll break the EMMC installation system.

Other than that I've resolved the systemD issue as described in #18 and #17 by chroot'ing in and downgrading the package, then telling pacman not to upgrade it. This fixes wifi and USB.
The systemd package currently comes from my dropbox, but I put the package on here, if this gets merged, i'll create another pull request updating the URL to get it from github.

I also added a prompt to set a root password, as in my experience, I was unable to login when i first booted the device because no root password was set.

### CODE REVIEW

**Comment by omgmog** [comment]
If this process works for you, cool. I won't merge it though as it changes the original script too substantially, introduces the requirement of a Linux machine for an initial step, etc.

Regarding the `prepare-usb.sh` part of your proposed process, in #14 I arrived at `parted` and `partprobe` possibly being available in `/usr/sbin`, but this simply not being available in `$PATH` by default, so maybe it's worth exploring that a bit more.

Thanks for your time getting this to work for you, if I had more time (and my Chromebook would actually power on!) I'd be working more towards making the script work.

Cheers!

**Comment by jman6495** [comment]
Cheers, I checked /usr/sbin and sadly they weren't availible. I'm on the latest stable build of chromeOS.
Is the systemd fix of interest ? If so i'll resubmit a merge request without the other modifications !

**Comment by omgmog** [comment]
systemd fix is definitely of interest, so that would be cool!

**Comment by starkers** [comment]
Am struggling due to the lack of ```partprobe``` on my book was annoying.. anyway I've cleaned that [script](https://github.com/omgmog/archarm-usb-hp-chromebook-11/pull/22) up for you and will be attempting it under chrome again shortly.

I did try a dd of ```hp11-arch-usb-2014-12-06.img``` onto a stick (16Gb if thats OK?) and sadly that didn't work either.. got this at boot:

Image

The device is quite new (got it for my wife but it sucks at presentations) so looking forward to using it for ssh+git+vim+zsh+i3

* Chrome: 40.0.2214.93 
* Model: SPRING G9B-D3C-A42

**Comment by jman6495** [comment]
@starkers try the prepare-usb script and do the partitioning on a desktop machine, once it's prepared just remove the part of the script that does the partitioning and let it continue from there on.

**Comment by starkers** [comment]
@jman6495 thanks for the suggestion but I already did, it simply spat out "some" error..  (I did'nt take a photo)


I'll try again soon.. and take a photo this time (sorry it was late and I had other experiments to try so I just moved on)

After that I did the dd and got what you see above.. can't make much sense of why it was erroring. 
Mounting the disk under normal linux work'ed OK also so the data was intact..

**Comment by jman6495** [comment]
@starkers I'm testing a potential other method now ! i'll keep you updated :)!

**Pull request closed without merging**
