### PR TITLE
fixed USB install part to match "official" guide

### PR DESCRIPTION
**Pull request by wamserma**
Adopted instructions from http://archlinuxarm.org/platforms/armv7/samsung/samsung-chromebook into script. Please ignore changes to README.md

### CODE REVIEW

**Comment by hitechredneck** [comment]
works perfectly.

**Comment by omgmog** [comment]
Yep confirmed as working here, I'll merge it manually though for clarity. Cheers!

**Comment by wamserma** [comment]
Thanks, will close the request.

**Comment by wamserma** [comment]
I'll reopen the PR, as starkers reported success[1] with his own script. Seems things are working with stock U-Boot and without self-signing the kernel. Will try and report.

[1] https://github.com/omgmog/archarm-usb-hp-chromebook-11/issues/40#issuecomment-145517045

**Comment by wamserma** [comment]
closed.

**Pull request closed without merging**
