### PR TITLE
Fixed some isntallation issues

### PR DESCRIPTION
**Pull request by nasufster**
Fixed some installation issues and improved the robustness if network connection fails. One of the issues (bootloader in butil_kernel) was already commented by a user. Implementing alsa state is optional and you may want to change the GITHUBUSER.

Cheers

### CODE REVIEW

**Comment by duck** [comment]
Do we still need to hold the version of systemd to 212-3?  It is currently up to 219-6 for ARM..

thanks!

d

**Comment by nasufster** [comment]
I guess we still need it. Last time I tried systemd 219 (4 days ago) the detection of the wifi module was failing i.e. no mlan0 interface. Did not have the time to dig what is the issue with 219. Could it be the older version of the arm kernel 3.4?

**Comment by omgmog** [comment]
Looks pretty good, but you're checking for `portage`, shouldn't that be `parted`? 

Portage is the package manager from Gentoo, isn't it?

**Comment by nasufster** [comment]
Yes you are right it is from Gentoo. Apparently we can use it on ChromeOS and install some other packages. As far as I understand we need portage in order to get parted. This is what dev_install is providing us. If dev_install fails due to bad network we need to do some cleaning otherwise we cannot get the portage and we are stuck.

**Comment by omgmog** [comment]
:+1: Well, I'll give your changes a run on my HP11 when I get a chance, and then we can see about getting this PR merged :)

**Comment by omgmog** [comment]
Merged in to https://github.com/omgmog/archarm-usb-hp-chromebook-11/tree/nasufster-rewrite-merge while I test, should be in master soon :)

**Pull request closed without merging**
